server:
  port: 18004
spring:
  application:
    name: isc-config-service
  datasource:
    url: jdbc:mysql://mysql-service:3306/biz_envoy?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&AppName=${spring.application.name}&AppVersion=1.0&AppSignature=NA&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 180000
      pool-name: panda.server-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 10

biz:
  url:
    f: http://localhost:18005
#    f: http://biz-envoy-f:18005
